#!/usr/bin/env bash
# Using a while loop to iterate over a range of numbers
counter=1

while [ $counter -le 11 ]
do
  if [ $counter != 10 ]; then
    echo "Best School"
  else
    echo "Hi"
  fi
  ((counter++))
done
