#!/usr/bin/env bash
# Using a while loop to iterate over a range of numbers
counter=1

while [ $counter -le 20 ]
do
  if [ $counter = 5 ]; then
    echo "bad luck from China"
    echo "$counter"
  elif [ $counter = 10 ]; then
    echo "$counter"
    echo "bad luck from Japan"
  elif [ $counter = 18 ]; then
    echo "bad luck from Italy"
    echo "$counter"
  else
    echo "$counter"
  fi
  ((counter++))
done
