#!/usr/bin/env bash
# Using a while loop to iterate over a range of numbers

for file in *; do
	if [[ $file != .* ]]; then
		name_after_dash=$(echo "$file" | cut -d'-' -f2-)
		echo "$name_after_dash"
	fi
done