#!/usr/bin/env bash
#Write a Bash script that creates an RSA key pair.

private_key_name="school"
key_bits=4096
passphrase="betty"

ssh-keygen -t rsa -b $key_bits -P "$private_key_name" -f "$passphrase"
